name: Build RSS JSON

on:
  schedule:
    - cron: "*/10 * * * *"   # כל 10 דקות (ייתכן ג׳יטר של גיטהאב)
  workflow_dispatch:         # הפעלה ידנית מה־UI

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build feeds.json
        run: |
          node -v
          node scripts/fetch_feeds.js

      - name: Commit & push data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/feeds.json
          git commit -m "chore: update feeds.json [skip ci]" || echo "No changes"
          git push